import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/features/query/QueryProvider";
import { ResponsiveContainer } from "@/components/ResponsiveContainer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProvider>
          <ResponsiveContainer>{children}</ResponsiveContainer>
          <Toaster 
            position="bottom-right"
            toastOptions={{
              style: {
                background: '#4E876D',
                color: '#fff',
              },
              success: {
                iconTheme: {
                  primary: '#fff',
                  secondary: '#4E876D',
                },
              },
              error: {
                style: {
                  background: '#ef4444',
                  color: '#fff',
                },
                iconTheme: {
                  primary: '#fff',
                  secondary: '#ef4444',
                },
              },
            }}
          />

        </QueryProvider>
      </body>
    </html>
  );
}
