import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/features/common/components/composites/Header";
import Category from "@/features/categories/components/Category";
import { Lato } from "next/font/google";
import { Categories } from "@/features/categories/components/Categories";
import Essential from "@/features/essentials/components/Essential";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${lato.className} min-w-full min-h-full flex flex-col`}>
        <div className="mx-auto">
          <Header />
        </div>
        <Category />
        <div className="mx-auto">{children}</div>
        <Essential />
      </body>
    </html>
  );
}
